# Use Node.js slim image as base
FROM node:20-slim

# Create app directory
WORKDIR /usr/src/app

# Copy package files and local dependencies
COPY package*.json ./
COPY zkusd-*.tgz ./

# Copy source code for building
COPY src/ src/
COPY tsconfig.json ./

# Install dependencies and build
RUN npm ci && \
    npm run build

# Clean up source files (optional, reduces image size)
RUN rm -rf src/

# Define build arguments with defaults
ARG NODE_ENV=development
ARG NETWORK=devnet
ARG BLOCKCHECK_INTERVAL=10
ARG MONGO_URI
ARG NUMBER_OF_ORACLES=3
ARG DEVNET_ORACLE_1_PRIVATE_KEY
ARG DEVNET_ORACLE_1_PUBLIC_KEY
ARG DEVNET_ORACLE_2_PRIVATE_KEY
ARG DEVNET_ORACLE_2_PUBLIC_KEY
ARG DEVNET_ORACLE_3_PRIVATE_KEY
ARG DEVNET_ORACLE_3_PUBLIC_KEY
ARG DEVNET_ORACLE_DUMMY_PRIVATE_KEY
ARG DEVNET_ORACLE_DUMMY_PUBLIC_KEY

# Set environment variables
ENV NODE_ENV=$NODE_ENV
ENV NETWORK=$NETWORK
ENV BLOCKCHECK_INTERVAL=$BLOCKCHECK_INTERVAL
ENV MONGO_URI=$MONGO_URI
ENV NUMBER_OF_ORACLES=$NUMBER_OF_ORACLES
ENV DEVNET_ORACLE_1_PRIVATE_KEY=$DEVNET_ORACLE_1_PRIVATE_KEY
ENV DEVNET_ORACLE_1_PUBLIC_KEY=$DEVNET_ORACLE_1_PUBLIC_KEY
ENV DEVNET_ORACLE_2_PRIVATE_KEY=$DEVNET_ORACLE_2_PRIVATE_KEY
ENV DEVNET_ORACLE_2_PUBLIC_KEY=$DEVNET_ORACLE_2_PUBLIC_KEY
ENV DEVNET_ORACLE_3_PRIVATE_KEY=$DEVNET_ORACLE_3_PRIVATE_KEY
ENV DEVNET_ORACLE_3_PUBLIC_KEY=$DEVNET_ORACLE_3_PUBLIC_KEY
ENV DEVNET_ORACLE_DUMMY_PRIVATE_KEY=$DEVNET_ORACLE_DUMMY_PRIVATE_KEY
ENV DEVNET_ORACLE_DUMMY_PUBLIC_KEY=$DEVNET_ORACLE_DUMMY_PUBLIC_KEY

# Start the service
CMD ["node", "dist/index.js"]